# -*- coding: utf-8 -*-
"""classify_ecg

Automatically generated by Colab.


"""

"""
 ECG classification: Normal vs Abnormal,using KNN .

After the signal processing  and the output being saved as a pickle file
This script covers:
  1. loading the preprocessed data
  2. artifact rejection
  3. class labels used are  2: Normal / Abnormal
  4. a single train/test split
  5. training and tuning a KNN classifier
  6. evaluating and printing results, and saving the model
"""

import numpy as np
import pickle
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, f1_score
from joblib import dump


# 1. Load preprocessed data


def load_ecg_data_matrix(filename='data_ecg.pickle'):
    """Load the dict produced after running download_preprocess_ecg.py."""
    with open(filename, 'rb') as f:
        data_dict = pickle.load(f)
    for key, v in data_dict.items():
        print(f'loaded {key}: {type(v)} {getattr(v, "shape", "")}')
    return data_dict



# 2. Artifact rejection
#    flags segments with excessive
#    variability or extreme negative amplitude as likely recording artifacts.
# ---------------------------------------------------------------------------

def remove_ecg_artifacts(data_all, annotations_all, onsets_all, pt_codes_all, n_sd=4):
    std = np.std(data_all, axis=1)
    std_th = std > np.mean(std) + n_sd * np.std(std)

    amp_max_neg = np.min(data_all, axis=1)
    amp_th = amp_max_neg < np.mean(amp_max_neg) - n_sd * np.std(amp_max_neg)

    keep = np.logical_and(~std_th, ~amp_th)

    n_removed = np.sum(~keep)
    print(f'Flagged {n_removed} out of {len(keep)} ECG segments as artifacts')

    return (data_all[keep, :], annotations_all[keep],
            onsets_all[keep], pt_codes_all[keep])



# 3. binary labels: Normal (0) vs Abnormal (1)


def make_binary_labels(annotations):
    keep_types = ['N', 'A', 'L', 'R', 'V']
    ix = np.isin(annotations.ravel(), keep_types)

    labels = np.zeros((ix.sum(), 1))
    ann_kept = annotations[ix].ravel()
    labels[ann_kept != 'N'] = 1  # everything non-normal -> Abnormal

    return ix, labels



# 4. Train/test split
#    Simplified  a single stratified split

def split_data_by_patient(data, labels, pt_codes, test_size=0.25, random_state=0):
    from sklearn.model_selection import GroupShuffleSplit

    pt_codes = np.ravel(pt_codes)
    gss = GroupShuffleSplit(n_splits=1, test_size=test_size, random_state=random_state)
    train_idx, test_idx = next(gss.split(data, labels.ravel(), groups=pt_codes))

    X_train, X_test = data[train_idx], data[test_idx]
    y_train, y_test = labels.ravel()[train_idx], labels.ravel()[test_idx]
    return X_train, X_test, y_train, y_test



# 5. Training and tuning KNN


def train_knn(X_train, y_train, k_values=(1, 3, 5, 10, 15, 20)):
    # 'weights' controls how neighbors vote:
    #   'uniform'  every neighbor counts equally
    #   'distance' closer neighbors count more than farther ones
    # Distance weighting often helps in imbalanced settings like this one,
    # since a genuinely close Abnormal neighbor won't get diluted by several
    # more-distant Normal neighbors.
    param_grid = {
        'n_neighbors': list(k_values),
        'weights': ['uniform', 'distance'],
    }
    clf = KNeighborsClassifier()
    clf = GridSearchCV(clf, param_grid, cv=5, n_jobs=-1, scoring='f1_macro')
    clf.fit(X_train, y_train)
    return clf



# 6. Evaluate + save


def evaluate(clf, X_test, y_test, label='Test set'):
    y_pred = clf.predict(X_test)
    print(f'\n--- {label} ---')
    print(classification_report(y_test, y_pred, target_names=['Normal', 'Abnormal']))
    print('Confusion matrix (rows=true, cols=pred):')
    print(confusion_matrix(y_test, y_pred))
    f1 = f1_score(y_test, y_pred, average='weighted')
    print(f'Weighted F1: {f1:.3f}')
    return y_pred, f1






if __name__ == '__main__':
    import json
    from datetime import datetime

    def log_results(y_test, y_pred, k, filename='results_log.json'):
        entry = {
            'timestamp': datetime.now().isoformat(),
            'best_k': k,
            'classification_report': classification_report(
                y_test, y_pred, target_names=['Normal', 'Abnormal'], output_dict=True
            ),
            'confusion_matrix': confusion_matrix(y_test, y_pred).tolist(),
        }
        try:
            with open(filename) as f:
                log = json.load(f)
        except FileNotFoundError:
            log = []
        log.append(entry)
        with open(filename, 'w') as f:
            json.dump(log, f, indent=2)
        print(f'Logged run to {filename}')

    #  load preprocessed output from download_preprocess_ecg.py
    data_dict = load_ecg_data_matrix('data_ecg.pickle')
    data_all = data_dict['data_all']
    annotations_all = data_dict['annotations_all']
    onsets_all = data_dict['onsets_all']
    pt_codes_all = data_dict['pt_codes_all']

    #  artifact rejection
    data_all, annotations_all, onsets_all, pt_codes_all = remove_ecg_artifacts(
        data_all, annotations_all, onsets_all, pt_codes_all
    )

    #  binary labels
    ix, labels = make_binary_labels(annotations_all)
    data = data_all[ix, :]

    print(f'\nClass balance -> Normal: {(labels == 0).sum()}, '
          f'Abnormal: {(labels == 1).sum()}')

    #  split by patient
    pt_codes = pt_codes_all[ix]
    X_train, X_test, y_train, y_test = split_data_by_patient(data, labels, pt_codes)

    #  train KNN
    clf = train_knn(X_train, y_train)
    print(f'\nBest params: k={clf.best_params_["n_neighbors"]}, '
          f'weights={clf.best_params_["weights"]}')

    # evaluate (capture y_pred)
    y_pred, f1 = evaluate(clf, X_test, y_test, label='Held-out test set (binary KNN)')

    # save model
    dump(clf, 'Model_kNN_binary.joblib')
    print('\nSaved model to Model_kNN_binary.joblib')

    #  log results
    log_results(y_test, y_pred, clf.best_params_['n_neighbors'])